### ISSUE TITLE
add SupplementaryFeatures options (such as public holidays)

### ISSUE THREAD

**Issue by pasard** [awslabs/improving-forecast-accuracy-with-machine-learning#1]
The solution does currently not allow to add **SupplementaryFeatures** such as public holidays.
It overwrites **InputDataConfig** when creating the Predictor without taking into account any SupplementaryFeatures passed in the _forecast-default_ config file.

**Comment by pwrmiller** [comment]
Thanks for your feedback and feature request @pasard ! I can confirm that this is the current behavior of the solution. We've put this into our backlog and will consider how to add this feature.

**Comment by pwrmiller** [comment]
This is now fixed in version 1.3.0!
